version: '3.8'

services:
  gwan-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://api.gwan.com.br/api}
        VITE_APP_NAME: ${VITE_APP_NAME:-Gwan IA}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
        VITE_BUILD_TIME: ${VITE_BUILD_TIME:-}
        VITE_GIT_COMMIT: ${VITE_GIT_COMMIT:-}
        VITE_GIT_BRANCH: ${VITE_GIT_BRANCH:-main}
    container_name: gwan-site
    restart: unless-stopped
    networks:
      - gwan
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gwan-site.rule=Host(`gwan.com.br`)"
      - "traefik.http.routers.gwan-site.entrypoints=websecure"
      - "traefik.http.routers.gwan-site.tls.certresolver=letsencrypt"
      - "traefik.http.services.gwan-site.loadbalancer.server.port=80"
      - "traefik.docker.network=gwan"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    environment:
      - NODE_ENV=production
      - VITE_API_URL=${VITE_API_URL}
      - VITE_APP_NAME=${VITE_APP_NAME}
      - VITE_APP_VERSION=${VITE_APP_VERSION}
      - VITE_BUILD_TIME=${VITE_BUILD_TIME}
      - VITE_GIT_COMMIT=${VITE_GIT_COMMIT}
      - VITE_GIT_BRANCH=${VITE_GIT_BRANCH}
      - VITE_DEBUG=${VITE_DEBUG}
      - VITE_LOG_LEVEL=${VITE_LOG_LEVEL}
      - VITE_SHOW_DEV_TOOLS=${VITE_SHOW_DEV_TOOLS}
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  gwan:
    external: true
