version: '3.8'

services:
  gwan-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3000/api}
        VITE_APP_NAME: ${VITE_APP_NAME:-Gwan IA}
        VITE_APP_VERSION: ${VITE_APP_VERSION:-1.0.0}
        VITE_BUILD_TIME: ${VITE_BUILD_TIME:-}
        VITE_GIT_COMMIT: ${VITE_GIT_COMMIT:-}
        VITE_GIT_BRANCH: ${VITE_GIT_BRANCH:-}
    container_name: gwan-site-local
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      # Ambiente
      - NODE_ENV=development
      
      # Aplicação
      - VITE_APP_NAME=${VITE_APP_NAME:-Gwan IA}
      - VITE_APP_VERSION=${VITE_APP_VERSION:-1.0.0}
      
      # API (local)
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api}
      
      # Build
      - VITE_BUILD_TIME=${VITE_BUILD_TIME:-}
      - VITE_GIT_COMMIT=${VITE_GIT_COMMIT:-}
      - VITE_GIT_BRANCH=${VITE_GIT_BRANCH:-}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
